#!/bin/sh
# fdsetup.sh - stress tester setup
# @(#) $Name$ $Id$
# Copyright (c) E2 Systems Limited 1993
#This forms driver script expects the following input parameters
#
#  1.  - Transaction Type (for creating the script files)
#  2.  - Run identifier (master PID)
#  3.  - Bundle number
#  4.  - character per second
#  5.  - think time per transaction
#  6.  - number of simultaneous users
#  7.  - number of transactions generated by echo file
#  8.  - runtype
#  9.  - para_1
#  10. - para_2
#  11. - para_3
#
# Processing:
#   - check the count of the number of parameters
#   - add the records needed to ensure that everything will be
#     valid given the scope of the run (ie. the foreign keys will
#     be present)
#   - generate the echo files
#
 if test $# -lt 9
 then 
 echo "$0: transaction pid bundle char/sec think/trnsction no/usrs no/trnsct user_id seed_value server_1 server_2" >&2 
	exit 1
 fi
#
# Assign script variables
#
# form identifies the generation script
form=$1
# pid is used as the run identifier
pid=$2
# Number of records added to the database per transaction
bundle=$3
# cps is the operator keying rate
cps=$4
# think is the operator think time
think=$5
# nusers is the number of users
nusers=$6
# ntrans is the number of transactions to execute for each user
ntrans=$7
# runtype "m" for multi-user
runtype=$8
# para_1 is normally used to control username in multi-user tests,
#    but can be anything
para_1=$9
shift
shift
para_2=$8
para_3=$9
#
# Generate the echo files, one per user.
#
g=0
if [ "$PATH_OS" = ULTRIX  -o "$PATH_OS" = AIX ]
then
  PATH_AWK=awk
elif [ "$PATH_OS" = OSF ]
then
  PATH_AWK=gawk
else
  PATH_AWK=nawk
fi
export PATH_AWK
while [ $g -lt $nusers ]
do
    $PATH_AWK -f $form pid=$pid bundle=$bundle g=$g runtype=$runtype cps=$cps think=$think ntrans=$ntrans para_1=$para_1 para_2=$para_2 para_3=$para_3 - < /dev/null >echo$pid.$bundle.$g &
g=`expr $g + 1`
done
#
# Wait until all done
#
wait
#
exit
