/*
 * termdef.h - Termcap/Terminfo Key names, used by code that recognises function
 * keys in the input.
 * @(#) $Name$ $Id$
 * Copyright (c) E2 Systems Limited 1993
 */
struct key_name_desc {
   char * t_name;
   char * t_desc;
   char * tf_name;
   char * tc_name;
} key_name_desc[] = {
#ifdef TERMCAP
 { "!1",  "sent by shifted save key"},
 { "!2",  "sent by shifted suspend key"},
 { "!3",  "sent by shifted undo key"},
 { "#1",  "sent by shifted help key"},
 { "#2",  "sent by shifted home key"},
 { "#3",  "sent by shifted input key"},
 { "#4",  "sent by shifted left-arrow key"},
 { "%0",  "sent by redo key"},
 { "%1",  "sent by help key"},
 { "%2",  "sent by mark key"},
 { "%3",  "sent by message key"},
 { "%4",  "sent by move key"},
 { "%5",  "sent by next-object key"},
 { "%6",  "sent by open key"},
 { "%7",  "sent by options key"},
 { "%8",  "sent by previous-object key"},
 { "%9",  "sent by print or copy key"},
 { "%a",  "sent by shifted message key"},
 { "%b",  "sent by shifted move key"},
 { "%c",  "sent by shifted next-object key"},
 { "%d",  "sent by shifted options key"},
 { "%e",  "sent by shifted previous-object key"},
 { "%f",  "sent by shifted print or copy key"},
 { "%g",  "sent by shifted redo key"},
 { "%h",  "sent by shifted replace key"},
 { "%i",  "sent by shifted right-arrow key"},
 { "%j",  "sent by shifted resume key"},
 { "&0",  "sent by shifted cancel key"},
 { "&1",  "sent by ref(erence) key"},
 { "&2",  "sent by refresh key"},
 { "&3",  "sent by replace key"},
 { "&4",  "sent by restart key"},
 { "&5",  "sent by resume key"},
 { "&6",  "sent by save key"},
 { "&7",  "sent by suspend key"},
 { "&8",  "sent by undo key"},
 { "&9",  "sent by shifted beg(inning) key"},
 { "*0",  "sent by shifted find key"},
 { "*1",  "sent by shifted cmd (command) key"},
 { "*2",  "sent by shifted copy key"},
 { "*3",  "sent by shifted create key"},
 { "*4",  "sent by shifted delete-char key"},
 { "*5",  "sent by shifted delete-line key"},
 { "*6",  "sent by select key"},
 { "*7",  "sent by shifted end key"},
 { "*8",  "sent by shifted clear-line key"},
 { "*9",  "sent by shifted exit key"},
 { "@0",  "sent by find key"},
 { "@1",  "sent by beg(inning) key"},
 { "@2",  "sent by cancel key"},
 { "@3",  "sent by close key"},
 { "@4",  "sent by cmd (command) key"},
 { "@5",  "sent by copy key"},
 { "@6",  "sent by create key"},
 { "@7",  "sent by end key"},
 { "@8",  "sent by enter/send key (unreliable)"},
 { "@9",  "sent by exit key"},
 { "CC",  "terminal settable command character in"},
 { "prototyp",  "e"},
 { "CM",  "(NP)    memory-relative cursor motion to row m,"},
 { "column",  "n"},
 { "DC",  "(NP*)   delete n characters"},
 { "DL",  "(NP*)   delete n lines"},
 { "DO",  "(NP*)   move cursor down n lines"},
 { "F1",  "sent by function key 11"},
 { "F2",  "sent by function key 12"},
 { "F3",  "sent by function key 13"},
 { "F4",  "sent by function key 14"},
 { "F5",  "sent by function key 15"},
 { "F6",  "sent by function key 16"},
 { "F7",  "sent by function key 17"},
 { "F8",  "sent by function key 18"},
 { "F9",  "sent by function key 19"},
 { "FA",  "sent by function key 20"},
 { "FB",  "sent by function key 21"},
 { "FC",  "sent by function key 22"},
 { "FD",  "sent by function key 23"},
 { "FE",  "sent by function key 24"},
 { "FF",  "sent by function key 25"},
 { "FG",  "sent by function key 26"},
 { "FH",  "sent by function key 27"},
 { "FI",  "sent by function key 28"},
 { "FJ",  "sent by function key 29"},
 { "FK",  "sent by function key 30"},
 { "FL",  "sent by function key 31"},
 { "FM",  "sent by function key 32"},
 { "FN",  "sent by function key 33"},
 { "FO",  "sent by function key 34"},
 { "FP",  "sent by function key 35"},
 { "FQ",  "sent by function key 36"},
 { "FR",  "sent by function key 37"},
 { "FS",  "sent by function key 38"},
 { "FT",  "sent by function key 39"},
 { "FU",  "sent by function key 40"},
 { "FV",  "sent by function key 41"},
 { "FW",  "sent by function key 42"},
 { "FX",  "sent by function key 43"},
 { "FY",  "sent by function key 44"},
 { "FZ",  "sent by function key 45"},
 { "Fa",  "sent by function key 46"},
 { "Fb",  "sent by function key 47"},
 { "Fc",  "sent by function key 48"},
 { "Fd",  "sent by function key 49"},
 { "Fe",  "sent by function key 50"},
 { "Ff",  "sent by function key 51"},
 { "Fg",  "sent by function key 52"},
 { "Fh",  "sent by function key 53"},
 { "Fi",  "sent by function key 54"},
 { "Fj",  "sent by function key 55"},
 { "Fk",  "sent by function key 56"},
 { "Fl",  "sent by function key 57"},
 { "Fm",  "sent by function key 58"},
 { "Fn",  "sent by function key 59"},
 { "Fo",  "sent by function key 60"},
 { "Fp",  "sent by function key 61"},
 { "Fq",  "sent by function key 62"},
 { "Fr",  "sent by function key 63"},
 { "Fs",  "sent by function key 64"},
 { "Ft",  "sent by function key 65"},
 { "Fu",  "sent by function key 66"},
 { "Fv",  "sent by function key 67"},
 { "Fw",  "sent by function key 68"},
 { "Fx",  "sent by function key 69"},
 { "Fy",  "sent by function key 70"},
 { "Fz",  "sent by function key 71"},
 { "K1",  "sent by keypad upper left"},
 { "K2",  "sent by keypad center"},
 { "K3",  "sent by keypad upper right"},
 { "K4",  "sent by keypad lower left"},
 { "K5",  "sent by keypad lower right"},
 { "k0",  "sent by function key 0"},
 { "k1",  "sent by function key 1"},
 { "k2",  "sent by function key 2"},
 { "k3",  "sent by function key 3"},
 { "k4",  "sent by function key 4"},
 { "k5",  "sent by function key 5"},
 { "k6",  "sent by function key 6"},
 { "k7",  "sent by function key 7"},
 { "k8",  "sent by function key 8"},
 { "k9",  "sent by function key 9"},
 { "k;",  "sent by function key 10"},
 { "kA",  "sent by insert-line key"},
 { "kB",  "sent by back-tab key"},
 { "kC",  "sent by clear-screen or erase key"},
 { "kD",  "sent by delete-character key"},
 { "kE",  "sent by clear-to-end-of-line key"},
 { "kF",  "sent by scroll-forward/down key"},
 { "kH",  "sent by home-down key"},
 { "kI",  "sent by insert-character or enter-insert-mode key"},
 { "kL",  "sent by delete-line key"},
 { "kM",  "sent by insert key while in insert mode"},
 { "kN",  "sent by next-page key"},
 { "kP",  "sent by previous-page key"},
 { "kR",  "sent by scroll-backward/up key"},
 { "kS",  "sent by clear-to-end-of-screen key"},
 { "kT",  "sent by set-tab key"},
 { "ka",  "sent by clear-all-tabs key"},
 { "kb",  "sent by backspace key"},
 { "kd",  "sent by down-arrow key"},
 { "kh",  "sent by home key"},
 { "kl",  "sent by left-arrow key"},
 { "kr",  "sent by right-arrow key"},
 { "kt",  "sent by clear-tab key"},
 { "ku",  "sent by up-arrow key"},
#else
{"ka1","KEY_A1, 0534, Upper left of keypad","key_a1","K1"},
{"ka3","KEY_A3, 0535, Upper right of keypad","key_a3","K3"},
{"kb2","KEY_B2, 0536, Center of keypad","key_b2","K2"},
{"kbs","KEY_BACKSPACE, 0407, Sent by BACKSPACE key","key_backspace","kb"},
{"kbeg","KEY_BEG, 0542, Sent by beg(inning) key","key_beg","@1"},
{"kcbt","KEY_BTAB, 0541, Sent by back-tab key","key_btab","kB"},
{"kc1","KEY_C1, 0537, Lower left of keypad","key_c1","K4"},
{"kc3","KEY_C3, 0540, Lower right of keypad","key_c3","K5"},
{"kcan","KEY_CANCEL, 0543, Sent by cancel key","key_cancel","@2"},
{"ktbc","KEY_CATAB, 0526, Sent by clear-all-tabs key","key_catab","ka"},
{"kclr","KEY_CLEAR, 0515, Sent by clear-screen or erase key","key_clear","kC"},
{"kclo","KEY_CLOSE, 0544, Sent by close key","key_close","@3"},
{"kcmd","KEY_COMMAND, 0545, Sent by cmd (command) key","key_command","@4"},
{"kcpy","KEY_COPY, 0546, Sent by copy key","key_copy","@5"},
{"kcrt","KEY_CREATE, 0547, Sent by create key","key_create","@6"},
{"kctab","KEY_CTAB, 0525, Sent by clear-tab key","key_ctab","kt"},
{"kdch1","KEY_DC, 0512, Sent by delete-character key","key_dc","kD"},
{"kdl1","KEY_DL, 0510, Sent by delete-line key","key_dl","kL"},
{"kcud1","KEY_DOWN, 0402, Sent by terminal down-arrow key","key_down","kd"},
{"krmir","KEY_EIC, 0514, Sent by rmir or smir in insert mode","key_eic","kM"},
{"kend","KEY_END, 0550, Sent by end key","key_end","@7"},
{"kent","KEY_ENTER, 0527, Sent by enter/send key","key_enter","@8"},
{"kel","KEY_EOL, 0517, Sent by clear-to-end-of-line key","key_eol","kE"},
{"ked","KEY_EOS, 0516, Sent by clear-to-end-of-screen key","key_eos","kS"},
{"kext","KEY_EXIT, 0551, Sent by exit key","key_exit","@9"},
{"kf0","KEY_F(0), 0410, Sent by function key f0","key_f0","k0"},
{"kf1","KEY_F(1), 0411, Sent by function key f1","key_f1","k1"},
{"kf2","KEY_F(2), 0412, Sent by function key f2","key_f2","k2"},
{"kf3","KEY_F(3), 0413, Sent by function key f3","key_f3","k3"},
{"kf4","KEY_F(4), 0414, Sent by function key f4","key_f4","k4"},
{"kf5","KEY_F(5), 0415, Sent by function key f5","key_f5","k5"},
{"kf6","KEY_F(6), 0416, Sent by function key f6","key_f6","k6"},
{"kf7","KEY_F(7), 0417, Sent by function key f7","key_f7","k7"},
{"kf8","KEY_F(8), 0420, Sent by function key f8","key_f8","k8"},
{"kf9","KEY_F(9), 0421, Sent by function key f9","key_f9","k9"},
{"kf10","KEY_F(10), 0422, Sent by function key f10","key_f10","k;"},
{"kf11","KEY_F(11), 0423, Sent by function key f11","key_f11","F1"},
{"kf12","KEY_F(12), 0424, Sent by function key f12","key_f12","F2"},
{"kf13","KEY_F(13), 0425, Sent by function key f13","key_f13","F3"},
{"kf14","KEY_F(14), 0426, Sent by function key f14","key_f14","F4"},
{"kf15","KEY_F(15), 0427, Sent by function key f15","key_f15","F5"},
{"kf16","KEY_F(16), 0430, Sent by function key f16","key_f16","F6"},
{"kf17","KEY_F(17), 0431, Sent by function key f17","key_f17","F7"},
{"kf18","KEY_F(18), 0432, Sent by function key f18","key_f18","F8"},
{"kf19","KEY_F(19), 0433, Sent by function key f19","key_f19","F9"},
{"kf20","KEY_F(20), 0434, Sent by function key f20","key_f20","FA"},
{"kf21","KEY_F(21), 0435, Sent by function key f21","key_f21","FB"},
{"kf22","KEY_F(22), 0436, Sent by function key f22","key_f22","FC"},
{"kf23","KEY_F(23), 0437, Sent by function key f23","key_f23","FD"},
{"kf24","KEY_F(24), 0440, Sent by function key f24","key_f24","FE"},
{"kf25","KEY_F(25), 0441, Sent by function key f25","key_f25","FF"},
{"kf26","KEY_F(26), 0442, Sent by function key f26","key_f26","FG"},
{"kf27","KEY_F(27), 0443, Sent by function key f27","key_f27","FH"},
{"kf28","KEY_F(28), 0444, Sent by function key f28","key_f28","FI"},
{"kf29","KEY_F(29), 0445, Sent by function key f29","key_f29","FJ"},
{"kf30","KEY_F(30), 0446, Sent by function key f30","key_f30","FK"},
{"kf31","KEY_F(31), 0447, Sent by function key f31","key_f31","FL"},
{"kf32","KEY_F(32), 0450, Sent by function key f32","key_f32","FM"},
{"kf33","KEY_F(13), 0451, Sent by function key f13","key_f33","FN"},
{"kf34","KEY_F(34), 0452, Sent by function key f34","key_f34","FO"},
{"kf35","KEY_F(35), 0453, Sent by function key f35","key_f35","FP"},
{"kf36","KEY_F(36), 0454, Sent by function key f36","key_f36","FQ"},
{"kf37","KEY_F(37), 0455, Sent by function key f37","key_f37","FR"},
{"kf38","KEY_F(38), 0456, Sent by function key f38","key_f38","FS"},
{"kf39","KEY_F(39), 0457, Sent by function key f39","key_f39","FT"},
{"kf40","KEY_F(40), 0460, Sent by function key f40","key_f40","FU"},
{"kf41","KEY_F(41), 0461, Sent by function key f41","key_f41","FV"},
{"kf42","KEY_F(42), 0462, Sent by function key f42","key_f42","FW"},
{"kf43","KEY_F(43), 0463, Sent by function key f43","key_f43","FX"},
{"kf44","KEY_F(44), 0464, Sent by function key f44","key_f44","FY"},
{"kf45","KEY_F(45), 0465, Sent by function key f45","key_f45","FZ"},
{"kf46","KEY_F(46), 0466, Sent by function key f46","key_f46","Fa"},
{"kf47","KEY_F(47), 0467, Sent by function key f47","key_f47","Fb"},
{"kf48","KEY_F(48), 0470, Sent by function key f48","key_f48","Fc"},
{"kf49","KEY_F(49), 0471, Sent by function key f49","key_f49","Fd"},
{"kf50","KEY_F(50), 0472, Sent by function key f50","key_f50","Fe"},
{"kf51","KEY_F(51), 0473, Sent by function key f51","key_f51","Ff"},
{"kf52","KEY_F(52), 0474, Sent by function key f52","key_f52","Fg"},
{"kf53","KEY_F(53), 0475, Sent by function key f53","key_f53","Fh"},
{"kf54","KEY_F(54), 0476, Sent by function key f54","key_f54","Fi"},
{"kf55","KEY_F(55), 0477, Sent by function key f55","key_f55","Fj"},
{"kf56","KEY_F(56), 0500, Sent by function key f56","key_f56","Fk"},
{"kf57","KEY_F(57), 0501, Sent by function key f57","key_f57","Fl"},
{"kf58","KEY_F(58), 0502, Sent by function key f58","key_f58","Fm"},
{"kf59","KEY_F(59), 0503, Sent by function key f59","key_f59","Fn"},
{"kf60","KEY_F(60), 0504, Sent by function key f60","key_f60","Fo"},
{"kf61","KEY_F(61), 0505, Sent by function key f61","key_f61","Fp"},
{"kf62","KEY_F(62), 0506, Sent by function key f62","key_f62","Fq"},
{"kf63","KEY_F(63), 0507, Sent by function key f63","key_f63","Fr"},
{"kfnd","KEY_FIND, 0552, Sent by find key","key_find","@0"},
{"khlp","KEY_HELP, 0553, Sent by help key","key_help","%1"},
{"khome","KEY_HOME, 0406, Sent by home key","key_home","kh"},
{"kich1","KEY_IC, 0513, Sent by ins-char/ enter ins-mode key","key_ic","kI"},
{"kil1","KEY_IL, 0511, Sent by insert-line key","key_il","kA"},
{"kcub1","KEY_LEFT, 0404, Sent by terminal left-arrow key","key_left","kl"},
{"kll","KEY_LL, 0533, Sent by home-down key","key_ll","kH"},
{"kmrk","KEY_MARK, 0554, Sent by mark key","key_mark","%2"},
{"kmsg","KEY_MESSAGE, 0555, Sent by message key","key_message","%3"},
{"kmov","KEY_MOVE, 0556, Sent by move key","key_move","%4"},
{"knxt","KEY_NEXT, 0557, Sent by next- object key","key_next","%5"},
{"knp","KEY_NPAGE, 0522, Sent by next-page key","key_npage","kN"},
{"kopn","KEY_OPEN, 0560, Sent by open key","key_open","%6"},
{"kopt","KEY_OPTIONS, 0561, Sent by options key","key_options","%7"},
{"kpp","KEY_PPAGE, 0523, Sent by previous-page key","key_ppage","kP"},
{"kprv","KEY_PREVIOUS, 0562, Sent by previous- object key","key_previous","%8"},
{"kprt","KEY_PRINT, 0532, Sent by print or copy key","key_print","%9"},
{"krdo","KEY_REDO, 0563, Sent by redo key","key_redo","%0"},
{"kref","KEY_REFERENCE, 0564, Sent by ref(erence) key","key_reference","&1"},
{"krfr","KEY_REFRESH, 0565, Sent by refresh key","key_refresh","&2"},
{"krpl","KEY_REPLACE, 0566, Sent by replace key","key_replace","&3"},
{"krst","KEY_RESTART, 0567, Sent by restart key","key_restart","&4"},
{"kres","KEY_RESUME, 0570, Sent by resume key","key_resume","&5"},
{"kcuf1","KEY_RIGHT, 0405, Sent by terminal right-arrow key","key_right","kr"},
{"ksav","KEY_SAVE, 0571, Sent by save key","key_save","&6"},
{"kBEG","KEY_SBEG, 0572, Sent by shifted beginning key","key_sbeg","&9"},
{"kCAN","KEY_SCANCEL, 0573, Sent by shifted cancel key","key_scancel","&0"},
{"kCMD","KEY_SCOMMAND, 0574, Sent by shifted command key","key_scommand","*1"},
{"kCPY","KEY_SCOPY, 0575, Sent by shifted copy key","key_scopy","*2"},
{"kCRT","KEY_SCREATE, 0576, Sent by shifted create key","key_screate","*3"},
{"kDC","KEY_SDC, 0577, Sent by shifted delete- char key","key_sdc","*4"},
{"kDL","KEY_SDL, 0600, Sent by shifted delete-line key","key_sdl","*5"},
{"kslt","KEY_SELECT, 0601, Sent by select key","key_select","*6"},
{"kEND","KEY_SEND, 0602, Sent by shifted end key","key_send","*7"},
{"kEOL","KEY_SEOL, 0603, Sent by shifted clear-line key","key_seol","*8"},
{"kEXT","KEY_SEXIT, 0604, Sent by shifted exit key","key_sexit","*9"},
{"kind","KEY_SF, 0520, Sent by scroll- forward/down key","key_sf","kF"},
{"kFND","KEY_SFIND, 0605, Sent by shifted find key","key_sfind","*0"},
{"kHLP","KEY_SHELP, 0606, Sent by shifted help key","key_shelp","#1"},
{"kHOM","KEY_SHOME, 0607, Sent by shifted home key","key_shome","#2"},
{"kIC","KEY_SIC, 0610, Sent by shifted input key","key_sic","#3"},
{"kLFT","KEY_SLEFT, 0611, Sent by shifted left-arrow key","key_sleft","#4"},
{"kMSG","KEY_SMESSAGE, 0612, Sent by shifted message key","key_smessage","%a"},
{"kMOV","KEY_SMOVE, 0613, Sent by shifted move key","key_smove","%b"},
{"kNXT","KEY_SNEXT, 0614, Sent by shifted next key","key_snext","%c"},
{"kOPT","KEY_SOPTIONS, 0615, Sent by shifted options key","key_soptions","%d"},
{"kPRV","KEY_SPREVIOUS, 0616, Sent by shifted prev key","key_sprevious","%e"},
{"kPRT","KEY_SPRINT, 0617, Sent by shifted print key","key_sprint","%f"},
{"kri","KEY_SR, 0521, Sent by scroll- backward/up key","key_sr","kR"},
{"kRDO","KEY_SREDO, 0620, Sent by shifted redo key","key_sredo","%g"},
{"kRPL","KEY_SREPLACE, 0621, Sent by shifted replace key","key_sreplace","%h"},
{"kRIT","KEY_SRIGHT, 0622, Sent by shifted right-arrow key","key_sright","%i"},
{"kRES","KEY_SRSUME, 0623, Sent by shifted resume key","key_srsume","%j"},
{"kSAV","KEY_SSAVE, 0624, Sent by shifted save key","key_ssave","!1"},
{"kSPD","KEY_SSUSPEND, 0625, Sent by shifted suspend key","key_ssuspend","!2"},
{"khts","KEY_STAB, 0524, Sent by set-tab key","key_stab","kT"},
{"kUND","KEY_SUNDO, 0626, Sent by shifted undo key","key_sundo","!3"},
{"kspd","KEY_SUSPEND, 0627, Sent by suspend key","key_suspend","&7"},
{"kund","KEY_UNDO, 0630, Sent by undo key","key_undo","&8"},
{"kcuu1","KEY_UP, 0403, Sent by terminal up-arrow key","key_up","ku"},
#endif
};
